### ISSUE TITLE
Platform name and vendor in platform manifest

### ISSUE THREAD

**Issue by idomingu** [JeanQuilbeufHuawei/draft-collected-data-manifest#20]
Two changes are proposed to further align platform manifest with YANG Catalog draft:

1. Rename `platform` leaf (see [link](https://github.com/JeanQuilbeufHuawei/draft-collected-data-manifest/blob/b8cf78b96c87a842a468f72406f42a7898adc3fa/yang/ietf-collected-data-platform-manifest%402021-10-15.yang#L64)) to `name` in the `platform` container. Using the same identifier for parent container and child leaf looks confusing.The platform manifest module could leverage the `name` leaf that YANG Catalog defines as part of the `vendor` subtree (see [link](https://yangcatalog.org/yang-search/show_node/yang-catalog/%2Fyc%3Acatalog%3Fcontainer%2Fyc%3Avendors%3Fcontainer%2Fyc%3Avendor%3Flist%2Fyc%3Aplatforms%3Fcontainer%2Fyc%3Aplatform%3Flist%2Fyc%3Aname%3Fleaf/2018-04-03)). 

2. Include a new `vendor` leaf within the `platform` container. This leaf is defined as part of the `implementation` container in YANG Catalog module (see [link](https://yangcatalog.org/yang-search/show_node/yang-catalog/%2Fyc%3Acatalog%3Fcontainer%2Fyc%3Amodules%3Fcontainer%2Fyc%3Amodule%3Flist%2Fyc%3Aimplementations%3Fcontainer%2Fyc%3Aimplementation%3Flist%2Fyc%3Avendor%3Fleaf/2018-04-03)).

**Comment by bclaise** [comment]
both changes make sense.

**Comment by JeanQuilbeufHuawei** [comment]
Done in 6bd93226fc11e6d81a7d29192df0d4219985004e
