### ISSUE TITLE
Suppress-redundancy

### ISSUE THREAD

**Issue by idomingu** [JeanQuilbeufHuawei/draft-collected-data-manifest#28]
The data-collection-manifest includes a leaf that determines whether suppress-redundancy is activated for a given subscription:

https://github.com/JeanQuilbeufHuawei/draft-collected-data-manifest/blob/0212a49beed0a0ef0c9046980c7da107269fa18f/yang/ietf-collected-data-manifest%402021-10-15.yang#L123-L128

As far as I know this feature is only support in gNMI protocol (named `suppress_redundant` field in the [gNMI spec](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#35152-stream-subscriptions)). In the case of YANG Push, there is no mention to this feature, so I'm assuming this is not supported in NETCONF or RESTCONF protocols.

Therefore, should we keep this leaf in the module?

**Comment by dr2lopez** [comment]
I’d say yes, unless you see a serious issue if the leaf is not interpreted. This way we'll keep the widest compatibility possible…

**Comment by idomingu** [comment]
Agree with @dr2lopez. Shall we close this issue @JeanQuilbeufHuawei?

**Comment by JeanQuilbeufHuawei** [comment]
Yes, let’s close it.
